apiVersion: batch/v1
kind: CronJob
metadata:
  name: dz-mcall-GIT_BRANCH
  labels:
    org: tz
    team: devops
    project: mcall
    environment: STAGING
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 2  # Number of pods to run simultaneously (default: 3)
      completions: 2  # Number of pods that must complete (default: 3)
      template:
        metadata:
          labels:
            org: tz
            team: devops
            project: mcall
            environment: STAGING
            app: dz-mcall-GIT_BRANCH
        spec:
          restartPolicy: OnFailure
          serviceAccountName: dz-mcall-GIT_BRANCH
          imagePullSecrets:
            - name: tz-registrykey
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
            - name: dz-mcall-GIT_BRANCH
              image: doohee323/dz-mcall:BUILD_NUMBER_PLACEHOLDER
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
              env:
              - name: GIT-BRANCH
                value: GIT_BRANCH
              - name: CONTAINER_ENV
                value: 'kubernetes'
              - name: LEADER_ELECTION
                value: 'true'
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              command: ["/app/mcall"]
              args: ["-c=/app/mcall.yaml"]
              volumeMounts:
              - name: logs-volume
                mountPath: /app/log/mcall
          volumes:
          - name: logs-volume
            emptyDir: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dz-mcall-GIT_BRANCH
  labels:
    org: tz
    team: devops
    project: mcall
    environment: STAGING

